-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 10:34:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema booking_praxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema booking_praxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booking_praxi` DEFAULT CHARACTER SET utf8 ;
USE `booking_praxi` ;

-- -----------------------------------------------------
-- Table `booking_praxi`.`Type_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Type_school` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `shortcut` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Field_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Field_study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `shortcut` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `Type_school_id` INT NOT NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Field_study_Type_school1_idx` (`Type_school_id` ASC) VISIBLE,
  CONSTRAINT `fk_Field_study_Type_school1`
    FOREIGN KEY (`Type_school_id`)
    REFERENCES `booking_praxi`.`Type_school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year_graduation` INT NOT NULL,
  `class` VARCHAR(255) NOT NULL,
  `letter_class` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Field_study_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Class_Field_study1_idx` (`Field_study_id` ASC) VISIBLE,
  CONSTRAINT `fk_Class_Field_study1`
    FOREIGN KEY (`Field_study_id`)
    REFERENCES `booking_praxi`.`Field_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `date_birthday` DATE NULL,
  `job_title` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `role` VARCHAR(255) NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `spravce` TINYINT NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL DEFAULT 'fa-regular fa-user',
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Class_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Class1_idx` (`Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `booking_praxi`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ico` VARCHAR(255) NOT NULL,
  `subject` TINYINT NOT NULL,
  `legal_form` INT NOT NULL,
  `decription` TEXT NULL,
  `city` VARCHAR(255) NOT NULL,
  `agree_document` TINYINT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `post_code` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NOT NULL DEFAULT 'fa-solid fa-building',
  `register_company` TINYINT NOT NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `contract_file` VARCHAR(255) NOT NULL,
  `end_new_offer` DATE NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Practise_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Practise_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `degree_before` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `degree_after` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `position_works` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Practise_manager_Company1_idx` (`Company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Practise_manager_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `booking_praxi`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Offer_practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Offer_practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `requirements` TEXT NULL,
  `description` TEXT NULL,
  `city` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `post_code` VARCHAR(255) NOT NULL,
  `copy_next_year` TINYINT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Practise_id` INT NOT NULL,
  `Practise_manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Offer_practise_Practise1_idx` (`Practise_id` ASC) VISIBLE,
  INDEX `fk_Offer_practise_Practise_manager1_idx` (`Practise_manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_Offer_practise_Practise1`
    FOREIGN KEY (`Practise_id`)
    REFERENCES `booking_praxi`.`Practise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offer_practise_Practise_manager1`
    FOREIGN KEY (`Practise_manager_id`)
    REFERENCES `booking_praxi`.`Practise_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Category_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Category_skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `descrtiption` TEXT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Category_skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Skill_Category_skill1_idx` (`Category_skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skill_Category_skill1`
    FOREIGN KEY (`Category_skill_id`)
    REFERENCES `booking_praxi`.`Category_skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Representative_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Representative_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `degree_before` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `degree_after` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `function` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Representative_company_Company1_idx` (`Company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Representative_company_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `booking_praxi`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Date_practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Date_practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  `Practise_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Date_practise_Practise1_idx` (`Practise_id` ASC) VISIBLE,
  CONSTRAINT `fk_Date_practise_Practise1`
    FOREIGN KEY (`Practise_id`)
    REFERENCES `booking_praxi`.`Practise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`User_has_Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`User_has_Skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Skill_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  INDEX `fk_User_has_Skill_Skill1_idx` (`Skill_id` ASC) VISIBLE,
  INDEX `fk_User_has_Skill_User1_idx` (`User_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_has_Skill_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking_praxi`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Skill_Skill1`
    FOREIGN KEY (`Skill_id`)
    REFERENCES `booking_praxi`.`Skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`User_has_Offer_practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`User_has_Offer_practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Offer_practise_id` INT NOT NULL,
  `accepted` TINYINT NULL,
  `like` TINYINT NOT NULL DEFAULT 0,
  `select` TINYINT NOT NULL DEFAULT 0,
  `edit_time` TIMESTAMP NULL,
  `create_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_has_Offer_practise_Offer_practise1_idx` (`Offer_practise_id` ASC) VISIBLE,
  INDEX `fk_User_has_Offer_practise_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Offer_practise_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking_praxi`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Offer_practise_Offer_practise1`
    FOREIGN KEY (`Offer_practise_id`)
    REFERENCES `booking_praxi`.`Offer_practise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Reset_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Reset_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `use` TINYINT NULL,
  `Representative_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reset_password_Representative_company1_idx` (`Representative_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reset_password_Representative_company1`
    FOREIGN KEY (`Representative_company_id`)
    REFERENCES `booking_praxi`.`Representative_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Class_has_Practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Class_has_Practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Class_id` INT NOT NULL,
  `Practise_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  INDEX `fk_Class_has_Practise_Practise1_idx` (`Practise_id` ASC) VISIBLE,
  INDEX `fk_Class_has_Practise_Class1_idx` (`Class_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Class_has_Practise_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `booking_praxi`.`Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_has_Practise_Practise1`
    FOREIGN KEY (`Practise_id`)
    REFERENCES `booking_praxi`.`Practise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Skill_has_Offer_practise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Skill_has_Offer_practise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Skill_id` INT NOT NULL,
  `Offer_practise_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Skill_has_Offer_practise_Offer_practise1_idx` (`Offer_practise_id` ASC) VISIBLE,
  INDEX `fk_Skill_has_Offer_practise_Skill1_idx` (`Skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skill_has_Offer_practise_Skill1`
    FOREIGN KEY (`Skill_id`)
    REFERENCES `booking_praxi`.`Skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skill_has_Offer_practise_Offer_practise1`
    FOREIGN KEY (`Offer_practise_id`)
    REFERENCES `booking_praxi`.`Offer_practise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Social_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Social_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Social_link_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Social_link_has_User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Social_link_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `del_time` TIMESTAMP NULL,
  INDEX `fk_Social_link_has_User_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Social_link_has_User_Social_link1_idx` (`Social_link_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Social_link_has_User_Social_link1`
    FOREIGN KEY (`Social_link_id`)
    REFERENCES `booking_praxi`.`Social_link` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Social_link_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking_praxi`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Log_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Log_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip_adrese` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Log_user_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Log_user_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking_praxi`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking_praxi`.`Log_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking_praxi`.`Log_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip_adrese` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `Representative_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Log_company_Representative_company1_idx` (`Representative_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Log_company_Representative_company1`
    FOREIGN KEY (`Representative_company_id`)
    REFERENCES `booking_praxi`.`Representative_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
